neoforge_version=21.11.45
packs=overlay-display,key-category-identifier,options-list,screen-field,world-gamerules,input-event,keybinds-options,text-components,server-119,light-color-getter,blocks-state,dirty-renderer,mobs-2111,renderer-state,items-components,data-criterion,holdersets-core,sodium-caffeine,leash-state,cmds-2111,reload-add-identifier
label=1.21.11
mc_range=[1.21.11]
neoforge_range=[21.11,)
java=21
sodium_version=mc1.21.11-0.8.15-beta.1
