neoforge_version=21.3.97
packs=options-list-legacy,world-flags,keybinds-options,overlay-display,key-category-string,screen-field,input-legacy,text-components,server-119,light-color,blocks-state,dirty-renderer,mobs-2105,renderer-state,items-components,data-location,holdersets-core,sodium-caffeine,leash-single,cmds-2005,reload-register,vanilla-120,displays,resources-map,frames-120
label=1.21.3
mc_range=[1.21.3]
neoforge_range=[21.3,21.4)
java=21
sodium_version=mc1.21.3-0.6.13
