neoforge_version=21.9.16-beta
packs=overlay-display,key-category-location,options-list-legacy,screen-field,world-flags,input-event,keybinds-options,text-components,server-119,light-color-getter,blocks-state,dirty-renderer,mobs-2105,renderer-state,items-components,data-location,holdersets-core,sodium-caffeine,leash-state,cmds-2105,reload-add-location,vanilla-120,displays,resources-map,frames-120
label=1.21.9-1.21.10
mc_range=[1.21.9,1.21.11)
neoforge_range=[21.9,21.11)
java=21
sodium_version=mc1.21.10-0.7.3
