neoforge_version=26.1.0.19-beta
packs=overlay-send,key-category-identifier,options-list,screen-field,world-difficulty,input-event,keybinds-options,text-components,server-119,light-coords-renderer,blocks-state,dirty-renderer,mobs-2111,renderer-state,items-components,data-criterion,holdersets-core,sodium-caffeine,leash-state,cmds-2111,reload-add-identifier
label=26.1-26.1.2
mc_range=[26.1,26.2)
neoforge_range=[26.1,26.2)
java=25
sodium_version=mc26.1.1-0.8.9
