neoforge_version=26.2.0.88
packs=text-components,options-list,screen-gui,keybinds-options,key-category-identifier,world-difficulty,server-119,input-event,light-coords,sodium-caffeine,blocks-state,dirty-extractor,mobs-2602,holdersets-core,renderer-state,items-components,data-identifier,overlay-send,leash-state,cmds-2111,reload-add-identifier
label=26.2
mc_range=[26.2,26.3)
neoforge_range=[26.2,26.3)
java=25
sodium_version=mc26.2-0.9.2
