modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/comedy01/Wick/issues"

[[mods]]
modId="wick"
version="${version}"
displayName="Wick"
displayURL="https://github.com/comedy01/Wick"
iconFile="assets/wick/icon128.png"
authors="comedy01"
description='''Dynamic lights. Hold a torch, lantern or lava bucket and the world lights up around you as you walk. Dropped torches, burning mobs and blazes shine too. Client-side only.'''

[[mixins]]
config="wick.mixins.json"

[[dependencies.wick]]
modId="neoforge"
type="required"
versionRange="${neoforge_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.wick]]
modId="minecraft"
type="required"
versionRange="${mc_range}"
ordering="NONE"
side="CLIENT"
