fabric_api_version=0.77.0+1.19.2
modmenu_version=4.1.2
packs=options-grid-1192,world-1192,keybinds-controls,overlay-display,key-category-string,screen-field,input-1192,keys-binding,text-components,server-119,light-color,blocks-getter,dirty-renderer,mobs-2001,renderer-legacy,items-nbt,data-json-1192,holdersets-1192,sodium-jellysquid,leash-none,cmds-nbt,indigo-light,vanilla-1192,displays-none,resources-map,frames-1192
label=1.19-1.19.2
range=>=1.19 <1.19.3
java=17
sodium_version=mc1.19.2-0.4.4
sodium_plain=true
sodium_runtime=org.joml:joml:1.10.4
fabric_api_id=fabric-api-base
fabric_loader_min=>=0.14.0
