fabric_api_version=0.100.8+1.20.6
modmenu_version=10.0.0
packs=options-grid,world-rules,keybinds-controls,overlay-display,key-category-string,screen-field,input-legacy,keys-binding,text-components,server-119,light-color,blocks-getter,dirty-renderer,mobs-2105,renderer-legacy,items-components,data-location,holdersets-core,sodium-jellysquid,leash-none,cmds-2005,indigo-light,vanilla-120,displays,resources-map,frames-120
label=1.20.5-1.20.6
range=>=1.20.5 <1.21
java=21
sodium_version=mc1.20.6-0.5.11
sodium_plain=true
fabric_loader_min=>=0.15.11
