fabric_api_version=0.97.3+1.20.4
modmenu_version=9.2.0
packs=options-grid,world-rules,keybinds-controls,overlay-display,key-category-string,screen-field,input-legacy,keys-binding,text-components,server-119,light-color,blocks-getter,dirty-renderer,mobs-2001,renderer-legacy,items-nbt,data-codec,holdersets-core,sodium-jellysquid,leash-none,cmds-nbt,indigo-light
label=1.20.2-1.20.4
range=>=1.20.2 <1.20.5
java=17
sodium_version=mc1.20.4-0.5.8
sodium_plain=true
