fabric_api_version=0.91.6+1.20.2
modmenu_version=8.0.1
packs=options-grid,world-legacy,keybinds-controls,overlay-display,key-category-string,screen-field,input-legacy,keys-binding,text-components,server-119,light-color,blocks-getter,dirty-renderer,mobs-2001,renderer-legacy,items-nbt,data-codec,holdersets-core,sodium-jellysquid,leash-none,cmds-nbt,indigo-light,vanilla-120,displays,resources-map,frames-120
label=1.20.2-1.20.4
range=>=1.20.2 <1.20.5
java=17
sodium_version=mc1.20.2-0.5.5
sodium_plain=true
