fabric_api_version=0.92.6+1.20.1
modmenu_version=7.2.2
packs=options-grid-legacy,world-legacy,keybinds-controls,overlay-display,key-category-string,screen-field,input-legacy,keys-binding,text-components,server-119,light-color,blocks-getter,dirty-renderer,mobs-2001,renderer-legacy,items-nbt,data-json,holdersets-core,sodium-jellysquid,leash-none,cmds-nbt,indigo-light,vanilla-120,displays,resources-map,frames-120
label=1.20-1.20.1
range=>=1.20 <1.20.2
java=17
sodium_version=mc1.20.1-0.5.13
fabric_loader_min=>=0.14.21
