fabric_api_version=0.141.6+1.21.11
modmenu_version=17.0.0
packs=overlay-display,key-category-identifier,options-list,screen-field,world-gamerules,input-event,keybinds-options,keys-binding,text-components,server-119,light-color-getter,blocks-state,dirty-renderer,mobs-2111,renderer-state,items-components,data-criterion,holdersets-core,sodium-caffeine,leash-state,cmds-2111,vanilla-120,displays,resources-map,frames-120
label=1.21.11
range=1.21.11
java=21
sodium_version=mc1.21.11-0.8.15-beta.1
