fabric_api_version=0.155.3+26.1.2
modmenu_version=18.0.1
packs=overlay-send,key-category-identifier,options-list,screen-field,world-difficulty,input-event,keybinds-options,keys-mapping,text-components,server-119,light-coords-renderer,blocks-state,dirty-renderer,mobs-2111,renderer-state,items-components,data-criterion,holdersets-core,sodium-caffeine,leash-state,cmds-2111,vanilla-120,displays,resources-map,frames-120
label=26.1-26.1.2
range=>=26.1 <26.2
java=25
sodium_version=mc26.1.1-0.8.9
