forge_version=1.18.2-40.3.12
mixinextras_version=0.5.5
packs=options-grid-1192,world-118,keybinds-controls,overlay-display,key-category-string,screen-field,input-1192,text-components-118,server-118,light-color,blocks-getter,dirty-renderer,mobs-2001,renderer-legacy,items-nbt,data-json-1192,holdersets-1192,sodium-jellysquid,leash-none,cmds-nbt,vanilla-1192,displays-none,resources-118,frames-118,forge-client-118
label=1.18.2
java=17
mc_range=[1.18.2,1.19)
forge_range=[40,)
loader_range=[40,)
pack_format=8
embeddium_version=0.3.18+mc1.18.2
