neoforge_version=1.20.1-47.1.106
mixinextras_version=0.5.5
packs=options-grid-legacy,world-legacy,keybinds-controls,overlay-display,key-category-string,screen-field,input-legacy,text-components,server-119,light-color,blocks-getter,dirty-renderer,mobs-2001,renderer-legacy,items-nbt,data-json,holdersets-core,sodium-jellysquid,leash-none,cmds-nbt,vanilla-120,displays,resources-map,frames-120,forge-client
label=1.20.1
java=17
mc_range=[1.20.1,1.20.2)
forge_range=[47,)
embeddium_version=0.3.31+mc1.20.1
loader_range=[47,)
pack_format=15
